name: "MyApp tvOS CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=13.3,name=Apple TV 4K"] #, "OS=11.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
    env:
      MINT_PATH: Mint
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - uses: actions/cache@v1
        with:
          path: Mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mint/metadata.json') }}
          restore-keys: |
            ${{ runner.os }}-mint-
      - name: Bootstrap
        run: make first_install
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "MyApp.xcodeproj" -scheme "MyApp_tvOS" -destination "${{ matrix.destination }}" clean test | xcpretty
